### ISSUE TITLE
Attempt to write a readonly database

### ISSUE THREAD

**Issue by muyiwao221** [Fmstrat/plex-db-sync#15]
bash-5.0# ./cron-script 
[Wed Sep 25 18:20:19 UTC 2019] Mounting sshfs for server 1...
[Wed Sep 25 18:20:19 UTC 2019] Starting.
[Wed Sep 25 18:20:19 UTC 2019] Stopping Plex on Server 1... Done
[Wed Sep 25 18:20:20 UTC 2019] Stopping Plex on Server 2... Done
[Wed Sep 25 18:20:23 UTC 2019] Checking for changes... Error: near line 1: attempt to write a readonly database
Found
Error: attempt to write a readonly database
Error: attempt to write a readonly database
Error: attempt to write a readonly database
Error: attempt to write a readonly database
Error: attempt to write a readonly database
Error: attempt to write a readonly database
Error: attempt to write a readonly database
Error: attempt to write a readonly database
Error: near line 1: attempt to write a readonly database
Error: near line 1: no such table: tmpdb.metadata_item_settings2
[Wed Sep 25 18:20:23 UTC 2019] Processing tags...
Error: no such table: taggings1
Error: no such table: taggings1
Error: no such table: taggings2
Error: no such table: taggings2
Error: attempt to write a readonly database
/plex-db-sync: line 417: declare: `-A': not a valid identifier
[Wed Sep 25 18:20:26 UTC 2019] Starting Plex on Server 1... Done
[Wed Sep 25 18:20:27 UTC 2019] Starting Plex on Server 2... Done
[Wed Sep 25 18:20:27 UTC 2019] Finished.
bash-5.0# 

Any idea what's up here? I used docker compose, but updated the plex-db-sync script because the version on github was newer. Also using the nocomparedb flag because even though it thinks the versions are different, both versions of plex are the same. Thanks.

**Comment by sh4des** [comment]
Is plex actually stopped on both servers? The command will fire off and state its stopped even if it fails.

**Comment by muyiwao221** [comment]
Yeah I just manually powered them down before running the script and I still get the exact same readout unfortunately

**Comment by muyiwao221** [comment]
Ah figured it out. For some reason the database directory wasn't writeable so it couldn't lock the database. It's all gucci now.
