### ISSUE TITLE
Possible to sync to new user?

### ISSUE THREAD

**Issue by skinnyzaz** [Fmstrat/plex-db-sync#16]
My GF and I decided to stop using the same account and use our own unique accounts.
I would like to sync all the watched content from our main account to the new user.

For example:
sync from server 1 user A to server 2 user B?
Then moving forward server 1 and 2 sync up user B like normal and same with user A

**Comment by Fmstrat** [comment]
If you look at the DB code, you can see how it's done, but in your particular use case, https://github.com/jacobwgillespie/plex-sync may be better. You can supply tokens for users with different usernames.
