### ISSUE TITLE
Question: Does this require the same path?

### ISSUE THREAD

**Issue by ghost** [Fmstrat/plex-db-sync#17]
We are trying to migrate plex from a bare metal install to a docker install and the path to the media is different. Meaning we need to re-add the media libraries and lose the watch data. Does this copy over the path for the media as well as watched status i.e. replacing the media path on the new server with the path from the old server?

**Comment by Fmstrat** [comment]
Yes, it matches on ID, not media path. However, if you're moving into Docker, it's much easier to just change the mount path in the container:

```
  - volumes:
    - /media/path/on/host:/media/path/on/host
```

**Comment by ghost** [comment]
Yes but we have several containers that access the data and were trying to standardize the paths. 

Just to confirm 

"Does this copy over the path for the media"
"Yes, it matches on ID, not media path"
Are you saying yes this will work for us or yes it does copy over the path? Your response seems to be in conflict from my understanding.

**Comment by Fmstrat** [comment]
It should work fine. Only the metadata is updated, while the path name is stored in the library table. That being said, back up first :)

**Comment by ghost** [comment]
Got it, thank you.
