### ISSUE TITLE
Changes no longer sync

### ISSUE THREAD

**Issue by sh4des** [Fmstrat/plex-db-sync#9]
Hey mate, i've been using your script for a few months now and it has worked flawlessly, until recently where it no longer syncs changes.

I am running PMS V1.15.4.994 on both servers. The debug logs show this output..

Checking for changes... [Thu May  9 01:23:47 UTC 2019] UP1: 2019-05-08 22:17:18 - UP2: 2019-05-09 11:21:43
Found
Error: near line 1: table tmpdb.metadata_items1 has 46 columns but 47 values were supplied
Error: near line 1: table tmpdb.metadata_items2 has 46 columns but 47 values were supplied

It then proceeds to try and check the tags and watch status, shows output of a run and applies the db changes, but i dont see any changes in watched status between the 2 servers - they remain out of sync.

Please assist (i can provide more logs and info if required)

**Comment by daxxi13** [comment]
Hi,

It seems better with this changes : [https://github.com/Fmstrat/plex-db-sync/pull/10](https://github.com/Fmstrat/plex-db-sync/pull/10)

**Comment by sh4des** [comment]
Awesome, thanks for the changes - i have been using it for the last few days since the column fix and not had a problem.
